/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matriculascolegio;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author davidbousquet
 */

public class MatricularAlumno extends javax.swing.JFrame {
    
    Connection conexion = Conexion.getConnection();
    boolean matriculaGenerada = false;
    int numMatricula = 0;
    
    /**
     * Creates new form MatricularAlumno
     */
    public MatricularAlumno() {
        initComponents();
        matriculaTextField.setEditable(false);
        generarDiasComboBox(0, Integer.parseInt(añoFechaComboBox.getSelectedItem().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        generarMatriculaButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        apellidoTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        direccionTextField = new javax.swing.JTextField();
        cursosComboBox = new javax.swing.JComboBox<>();
        matricularBoton = new javax.swing.JButton();
        cancelarMatriculaButton = new javax.swing.JButton();
        mesFechaComboBox = new javax.swing.JComboBox<>();
        añoFechaComboBox = new javax.swing.JComboBox<>();
        diaFechaComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        rutTextField = new javax.swing.JTextField();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        nombreApoderadoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Matricular Alumno");

        jLabel2.setText("Matricula: ");

        matriculaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaTextFieldActionPerformed(evt);
            }
        });

        generarMatriculaButton.setText("Generar ");
        generarMatriculaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarMatriculaButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Fecha nac:");

        jLabel6.setText("Sexo:");

        jLabel7.setText("Correo:");

        jLabel8.setText("Teléfono:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("Curso: ");

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        cursosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pre-Kinder", "1B", "2B", "3B", "4B", "5B", "6B", "7B", "8B", "1M", "2M", "3M", "4M" }));

        matricularBoton.setText("Matricular");
        matricularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularBotonActionPerformed(evt);
            }
        });

        cancelarMatriculaButton.setText("Cancelar");
        cancelarMatriculaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarMatriculaButtonActionPerformed(evt);
            }
        });

        mesFechaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesFechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFechaComboBoxActionPerformed(evt);
            }
        });

        añoFechaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        añoFechaComboBox.setSelectedItem(mesFechaComboBox);
        añoFechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoFechaComboBoxActionPerformed(evt);
            }
        });

        diaFechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaFechaComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Rut:");

        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jLabel12.setText("Nombre Apoderado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(añoFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(mesFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(diaFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cancelarMatriculaButton)
                                                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(generarMatriculaButton))))
                                        .addComponent(jLabel1)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(113, 113, 113)
                                            .addComponent(rutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(13, 13, 13))))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(matricularBoton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarMatriculaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nombreApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mesFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricularBoton)
                    .addComponent(cancelarMatriculaButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaTextFieldActionPerformed

    private void generarMatriculaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarMatriculaButtonActionPerformed

        
        if (!matriculaGenerada){
            try {
                // TODO add your handling code here:
                numMatricula = Controlador.generarMatricula(conexion);
                matriculaGenerada = true;
                matriculaTextField.setText(String.valueOf(numMatricula));
                matriculaTextField.setEditable(false);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } 
        } else {
            JOptionPane.showMessageDialog(null,"Nº de matricula ya generado. Completar datos del alumno para matricular","Matricula existe", JOptionPane.DEFAULT_OPTION);
        }


    }//GEN-LAST:event_generarMatriculaButtonActionPerformed

    private void matricularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularBotonActionPerformed
            //TODO add your handling code here:
            matricularBoton();

    }//GEN-LAST:event_matricularBotonActionPerformed

    private void cancelarMatriculaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarMatriculaButtonActionPerformed
        // TODO add your handling code here:
        if (matriculaGenerada) {
        Controlador.cancelarMatricula(conexion, numMatricula);
        matriculaGenerada = false;
        JOptionPane.showMessageDialog(null,"Matricula "+numMatricula+" eliminada del sistema");
        numMatricula = 0;
        matriculaTextField.setText(String.valueOf(numMatricula));
        } else {
            JOptionPane.showMessageDialog(null, "Ninguna matricula creada para cancelar. Debes generar nueva primero");
        }


    }//GEN-LAST:event_cancelarMatriculaButtonActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void mesFechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFechaComboBoxActionPerformed
        // TODO add your handling code here:
        int mesSeleccionado = mesFechaComboBox.getSelectedIndex();
        generarDiasComboBox(mesSeleccionado, Integer.parseInt(añoFechaComboBox.getSelectedItem().toString()));
        
    }//GEN-LAST:event_mesFechaComboBoxActionPerformed

    private void diaFechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaFechaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaFechaComboBoxActionPerformed

    private void añoFechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoFechaComboBoxActionPerformed
        // TODO add your handling code here:
        int mesSeleccionado = mesFechaComboBox.getSelectedIndex();
        generarDiasComboBox(mesSeleccionado, Integer.parseInt(añoFechaComboBox.getSelectedItem().toString()));
    }//GEN-LAST:event_añoFechaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void generarDiasComboBox(int idMes, int año) {
        idMes +=1;
        int i;
        boolean bisiesto;
        bisiesto = año % 4 == 0;
        
        switch(idMes) {
            case 1:
                i = 31;
                break;
            case 2:
                i = 28;
                if(bisiesto) i = 29;
                break;
            case 3:
                i = 31;   
                break;
            case 4:
                i = 30;
                break;
            case 5:
                i = 31;
                break;
            case 6:
                i = 30;
                break;
            case 7:
                i = 31;
                break;
            case 8:
                i = 31;
                break;
            case 9:
                i = 30;
                break;
            case 10:
                i = 31;
                break;
            case 11:
                i = 30;
                break;
            case 12:
                i = 31;
                break;
            default:
                i = 0;
        }
        
        diaFechaComboBox.removeAllItems();
        
        for(int j=0;j<i;j++){
            diaFechaComboBox.addItem(String.valueOf(j+1));
        }
        
        
        
    }
    
    public void matricularBoton() {
        Alumno alumno = Alumno.getInstance();
        boolean isNull = true;
        int idMatricula;
        String nombre, apellido, fechaNac, nombreApoderado, correo, direccion, idCurso, rut, telefono;
        char sexo;
        
        
        idMatricula = numMatricula;
        if(idMatricula != 0) {
            alumno.setIdMatricula(idMatricula);
        } else {
            isNull = true;
        }
        
        nombre = nombreTextField.getText();
        if(!nombre.isEmpty()){
            alumno.setNombre(nombre);
        }
        
        apellido = apellidoTextField.getText();
        if(!apellido.isEmpty()){
            alumno.setApellido(apellido);
        }
       
        rut = rutTextField.getText();
        if(!rut.isEmpty()){
            alumno.setRut(Integer.parseInt(rut));
        }
        
        nombreApoderado = nombreApoderadoTextField.getText();
        if (!nombreApoderado.isEmpty()) {
            alumno.setNombreApoderado(nombreApoderado);
        }
        
        fechaNac = añoFechaComboBox.getSelectedItem().toString()+"-"+(mesFechaComboBox.getSelectedIndex()+1)+"-"+diaFechaComboBox.getSelectedItem().toString();
        alumno.setFechaNac(fechaNac);
        
        if (sexoComboBox.getSelectedIndex() == 0) {
            sexo = "F".charAt(0);
        } else {
            sexo = "M".charAt(0);
        }
        alumno.setSexo(sexo);
        
        correo = correoTextField.getText();
        if (!correo.isEmpty()) {
            alumno.setCorreo(correo);
        }
        
        telefono = telefonoTextField.getText();
        if (!telefono.isEmpty()) {
            alumno.setTelefono(Integer.parseInt(telefono));
        }
        
        direccion = direccionTextField.getText();
        if (!direccion.isEmpty()) {
            alumno.setDireccion(direccion);
        }
        
        switch(cursosComboBox.getSelectedIndex()){
            case 0:
                idCurso = "PB";
                break;
            case 1:
                idCurso = "1T";
                break;
            case 2: 
                idCurso = "2T";
                break;
            case 3: 
                idCurso = "3T";
                break;
            case 4:
                idCurso = "4T";
                break;
            case 5:
                idCurso = "5T";
                break;
            case 6: 
                idCurso = "6T";
                break;
            case 7: 
                idCurso = "7T";
                break;
            case 8:
                idCurso = "8T";
                break;
            case 9:
                idCurso = "11T";
                break;
            case 10:
                idCurso = "12T";
                break;
            case 11:
                idCurso = "13T";
                break;
            case 12:
                idCurso = "14T";
                break;
            default:
                idCurso = "1T";
        }
        
        alumno.setIdCurso(idCurso);
        
        /*
        int idMatricula;
        String nombre, apellido, fechaNac, nombreApoderado, correo, direccion, idCurso, rut, telefono;
        char sexo;
        */
        isNull = (nombre.equals("") | apellido.equals("") | nombreApoderado.equals("") | correo.equals("") | direccion.equals("") | rut.equals("") | telefono.equals("") );
        if (!isNull) {
            Controlador.matricularAlumno(conexion, alumno);
        } else {
            JOptionPane.showMessageDialog(null, "Faltan datos para matricular.");
        }
        
    }
    
    
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatricularAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatricularAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatricularAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatricularAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatricularAlumno().setVisible(true);
            }
        });
    }
    
    
    

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JComboBox<String> añoFechaComboBox;
    private javax.swing.JButton cancelarMatriculaButton;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JComboBox<String> cursosComboBox;
    private javax.swing.JComboBox<String> diaFechaComboBox;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JButton generarMatriculaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JButton matricularBoton;
    private javax.swing.JComboBox<String> mesFechaComboBox;
    private javax.swing.JTextField nombreApoderadoTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField rutTextField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables


}
